# Generated by Django 2.2.4 on 2019-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190904_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default=('new', 'Новая'), max_length=8, verbose_name='Статус'),
        ),
    ]
