# Generated by Django 2.2.4 on 2019-09-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190904_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='done_date',
            field=models.DateField(default=None, verbose_name='Дата выполнения'),
        ),
    ]
