# Generated by Django 2.2.4 on 2019-09-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190905_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='done_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выполнения'),
        ),
    ]
