# Generated by Django 2.2.4 on 2019-09-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190905_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Tasks',
        ),
    ]
