# Generated by Django 2.2.4 on 2019-09-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190906_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='detailed_description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Детальное описание'),
        ),
    ]
