# Generated by Django 2.2.4 on 2019-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_tasks_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Детальное описание'),
        ),
    ]
